/* Replace with your SQL commands */
/*
DROP DATABASE IF EXISTS dev;
CREATE DATABASE dev;

DROP DATABASE IF EXISTS test;
CREATE DATABASE test;

GRANT ALL PRIVILEGES ON DATABASE dev TO eu;
GRANT ALL PRIVILEGES ON DATABASE test TO eu;
*/